name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
env:
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: 'Checkout Source Code'
      uses: actions/checkout@v2
    - name: 'Install .NET Core 6.0.x SDK'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: 'Restore .NET Dependencies'
      run: dotnet restore
    - name: 'Execute Dotnet Build'
      run: dotnet build --no-restore
    - name: 'Execute Dotnet Test'
      run: dotnet test --no-build --verbosity normal